# -------------------------------
# Academic Homepage Configuration
# -------------------------------

# Site settings
title: "Xiang Chen"  # Your name or site title
email: "your-email@example.com"  # Your email address
description: "Academic homepage of Xiang Chen. Research in Geospatial Statistics & Public Health."  # Short site description
author: "Xiang Chen"  # Your name
logo: "/assets/img/profile.png"  # Path to your profile picture
favicon: "/assets/images/favicon.ico"  # Path to favicon (if available)

# URL settings
baseurl: ""  # Leave empty if using https://ChenXiang1998.github.io/, or set to "/homepage" for subdirectories
url: "https://ChenXiang1998.github.io"  # Your website URL

# Timezone
timezone: Asia/Riyadh  # Set your local timezone

# Social links
social:
  github: "ChenXiang1998"
  google_scholar: "https://scholar.google.com.hk/citations?user=-_-FfdQAAAAJ&hl=zh-CN"
  orcid: "https://orcid.org/0000-0002-0573-9651"

# -------------------------------
# Jekyll Settings
# -------------------------------

markdown: kramdown  # Markdown processor
plugins:
  - jekyll-email-protect  # Protects email addresses from spam
  - jekyll-feed  # Generates an RSS feed
  - jekyll-seo-tag  # SEO optimizations
  - jekyll-sitemap  # Generates a sitemap for search engines

# Collections
collections:
  publications:
    output: true  # Enable a publications page
    permalink: /publications/:path/  # Set URL structure
  news:
    output: true  # Enable a news page
    permalink: /news/:path/
  showcase:
    output: true  # Enable a showcase/projects page
    permalink: /showcase/:path/

# Navigation Menu (Edit to change menu items)
navigation:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Publications"
    url: "/publications/"
  - title: "Projects"
    url: "/showcase/"
  - title: "News"
    url: "/news/"
  - title: "CV"
    url: "/cv/"
  - title: "Contact"
    url: "/contact/"

# Exclusions (Files to ignore when building the site)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Footer Configuration
footer:
  show_copyright: true  # Display copyright notice
  show_powered_by: true  # Display "Powered by Jekyll"
  additional_text: "© 2025 Xiang Chen. All rights reserved."

